### ISSUE TITLE
Comments on manuscript

### ISSUE THREAD

**Issue by osorensen** [Amalan-ConStat/R-fitODBOD#3]
Here are my comments on the [manuscript submitted to JOSS](https://github.com/openjournals/joss-reviews/issues/1505). You might have to open it with Adobe Acobat Reader (freely available at https://get.adobe.com/reader/) for the comments to show correctly.

Click this link to open the reviewed manuscript: [10.21105.joss.01505.pdf](https://github.com/Amalan-ConStat/R-fitODBOD/files/3293085/10.21105.joss.01505.pdf)

**Comment by Amalan-ConStat** [comment]
I will address the comments soon and will update the repository. Thank you.

**Comment by Amalan-ConStat** [comment]
1. List of dependencies have been added clearly.
2. Readme file in GitHub now contains a more clear view of the modeling process from step 1 to 5.
3. Yes, tests for functions are stored in the tests directory, they are unit tests using testthat package.
4. References has been changed accordingly where only 'doi' is added, but one article and book does not hold any 'doi' reference.

**Comment by osorensen** [comment]
Thanks. The updated manuscript addresses all my concerns.
