### ISSUE TITLE
EstMLE methods

### ISSUE THREAD

**Issue by osorensen** [Amalan-ConStat/R-fitODBOD#4]
This is part of my [review of your JOSS submission](https://github.com/openjournals/joss-reviews/issues/1505).

Having to use `suppressWarnings()` in order to use `bbmle::mle2` does not seem like best practice to me.

- First, why does `bbmle::mle2` give warnings in the first place, and are they harmless?
- Second, if `suppressWarnings()` is absolutely necessary, could you hide it with a wrapper function?

Regarding my second point, I am thinking about the following call:

```r
parameters=suppressWarnings(bbmle::mle2(EstMLEGrassiaIIBin,start = list(a=0.1,b=0.1),
data = list(x=No.D.D,freq=Obs.fre.1)))
```

You could define the function `EstMLEGrassiaIIBin` such that it calls `bbmle::mle2` with the right parameters, abstracting away this complexity for the user. I have here used `.EstMLEGrassiaIIBin` to denote the current `EstMLEGrassiaIIBin`. This would now be a non-exported worker function which the user does not interact with.

```r
# Suggested new function definition:
EstMLEGrassiaIIBin <- function(x, freq, a_start = 0.1, b = 0.1){
  parameters=suppressWarnings(bbmle::mle2(.EstMLEGrassiaIIBin,start = list(a=a_start,b=b_start),
data = list(x=x,freq=freq)))

  return(parameters)
}

```

The user could then just write, in the same manner as for the MGF method.

```r
EstMLEGrassiaIIBin(x, freq)
```

The same applies to the other EstMLE method.

**Comment by Amalan-ConStat** [comment]
@osorensen ,Thank you, First the warnings are harmless and they do occur when the Log likelihood values are NAN for some non convergent iterations of the optimization of given parameters. This does not harm the analysis at any point. Further, yes it is possible to hide it with a wrapper function, which i am able to do and submit.

**Comment by osorensen** [comment]
@Amalan-ConStat , thanks for the answers. In my opinion a wrapper function would make life easier for the user. In addition, `suppressWarnings` also suppresses warnings that may be useful to be aware of, and hence I do not think it is good practice to use it by default.

The following example illustrates some different calls to `bbmle::mle2`, including a case where the warning should not be ignored:

``` r
library(fitODBOD)
#> Hello, This is Amalan. For more details refer --> https://amalan-constat.github.io/R-fitODBOD/index.html

# Estimate shape parameters of Beta-Binomial Distribution
bbmle::mle2(EstMLEBetaBin, start = list(a = .1, b = .1),
            data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2))
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> Warning in beta(a + data[i], n + b - data[i]): NaNs produced
#> Warning in beta(a, b): NaNs produced
#> 
#> Call:
#> bbmle::mle2(minuslogl = EstMLEBetaBin, start = list(a = 0.1, 
#>     b = 0.1), data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2))
#> 
#> Coefficients:
#>         a         b 
#> 0.8575483 0.7007740 
#> 
#> Log-likelihood: -821.39

# Suppress the warnings of the above call
suppressWarnings(
  bbmle::mle2(EstMLEBetaBin, start = list(a = .1, b = .1),
              data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2))
  
)
#> 
#> Call:
#> bbmle::mle2(minuslogl = EstMLEBetaBin, start = list(a = 0.1, 
#>     b = 0.1), data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2))
#> 
#> Coefficients:
#>         a         b 
#> 0.8575483 0.7007740 
#> 
#> Log-likelihood: -821.39

# What if the user tries to set lower bounds on a and b: This gives a warning
# message that should not be ignored
bbmle::mle2(EstMLEBetaBin, start = list(a = .1, b = .1),
            data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2),
            lower = c(0, 0))
#> Warning in optim(par = c(a = 0.1, b = 0.1), fn = function (p) : bounds can
#> only be used with method L-BFGS-B (or Brent)
#> 
#> Call:
#> bbmle::mle2(minuslogl = EstMLEBetaBin, start = list(a = 0.1, 
#>     b = 0.1), data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2), 
#>     lower = c(0, 0))
#> 
#> Coefficients:
#>         a         b 
#> 0.8575367 0.7007644 
#> 
#> Log-likelihood: -821.39

# However, when using suppressWarnings, the user will not see the relevant
# warning about the lower bound not being used.
suppressWarnings(
  bbmle::mle2(EstMLEBetaBin, start = list(a = .1, b = .1),
              data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2),
              lower = c(0, 0))
  
)
#> 
#> Call:
#> bbmle::mle2(minuslogl = EstMLEBetaBin, start = list(a = 0.1, 
#>     b = 0.1), data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2), 
#>     lower = c(0, 0))
#> 
#> Coefficients:
#>         a         b 
#> 0.8575367 0.7007644 
#> 
#> Log-likelihood: -821.39

# If method is set to L-BFGS-B, however, the lower bounds are used and there
# should be no warning
bbmle::mle2(EstMLEBetaBin, start = list(a = .1, b = .1),
            method = "L-BFGS-B",
            data = list(x = Alcohol_data$Days, freq = Alcohol_data$week2),
            lower = c(0, 0))
#> 
#> Call:
#> bbmle::mle2(minuslogl = EstMLEBetaBin, start = list(a = 0.1, 
#>     b = 0.1), method = "L-BFGS-B", data = list(x = Alcohol_data$Days, 
#>     freq = Alcohol_data$week2), lower = c(0, 0))
#> 
#> Coefficients:
#>         a         b 
#> 0.8575367 0.7007644 
#> 
#> Log-likelihood: -821.39
```

<sup>Created on 2019-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Because of this, I would absolutely prefer if you made wrapper functions.

**Comment by Amalan-ConStat** [comment]
@osorensen , Thank you for the suggestion. Yes I have noticed what you are referring here. In order to resolve that 
1). I have written my own wrapper function, which would target the warnings if "NaN" is mentioned. Will that be okay !, therefore other warnings will be safe. 
2). Further, using "L-BFGS-B" method does work for most of the EstMLExxx functions (from the BMD), but this is not the case for ABD.

EstMLEBetaBin<-function(x,freq,a,b,...)
{
#new suppresswarning to only focus on when "NaN" is mentioned
  suppressWarnings2 <-function(expr, regex=character())
  {
    withCallingHandlers(expr, warning=function(w)
    {
      if (length(regex) == 1 && length(grep(regex, conditionMessage(w))))
      {
        invokeRestart("muffleWarning")
      }
    }                  )
  }
  suppressWarnings2(bbmle::mle2(.EstMLEBetaBin,data=list(x=x,freq=freq),
                      start = list(a=a,b=b),...),"NaN")
}

.EstMLEBetaBin<-function(x,freq,a,b)
{
  #with respective to using bbmle package function mle2 there is no need impose any restrictions
  #therefor the output is directly a single numeric value for the negative log likelihood value of
  #beta binomial distribution
  n<-max(x)
  data<-rep(x,freq)
  i<-1:sum(freq)
  term1<-sum(log(choose(n,data[i])))
  term2<-sum(log(beta(a+data[i],n+b-data[i])))
  BetaBinLL<-term1+term2-sum(freq)*log(beta(a,b))
  return(-BetaBinLL)
}

**Comment by osorensen** [comment]
Yes, @Amalan-ConStat , I think this looks good. And the `@export` statement should then be above `EstMLEBetaBin`, and not above `.EstMLEBetaBin`, right?

**Comment by Amalan-ConStat** [comment]
Yes, that is correct. sorry for that mistake. Also, will there be any issues if the user uses another language.
I did use the phrase "NaNs produced" before but it does not work for the French language that is why i reduced the phrase to "NaN".

**Comment by Amalan-ConStat** [comment]
Issues regarding warning messages have been resolved. Now only errors occur based on inappropriate inputs.

**Comment by osorensen** [comment]
This looks good. Closing the issue.
